name: 3-bs-firefox-smoke

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'master'
      - 'develop'
      - 'release/**'
env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  bs-firefox-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make check-docker-file-exists
      - run: make run-behave-browserstack
    env:
      BEHAVE_TAGS: "@smoke_test"
      OS: Windows
      OS_VERSION: 10
      BROWSER: Firefox
      BROWSER_VERSION: 73.0
